import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
function getFunction(name){const start=source.indexOf(`function ${name}(`);const end=source.indexOf('\n}',start)+2;return source.slice(start,end);}
test('email stays masked in default account display',()=>{const line=source.match(/function maskEmail[^\n]+/)[0];const context=vm.createContext({});vm.runInContext(line,context);assert.equal(context.maskEmail('ceo@thefa.kr'),'ce***@thefa.kr');assert.equal(context.maskEmail(''),'계정');assert.ok(source.includes("$('#session-full-email').textContent = email"));assert.ok(!source.includes(".title = model.state?.auth?.email"));});
test('AVA wizard cannot call backend or persist personal drafts',()=>{const preview=source.slice(source.indexOf('const avaRoles'));const definition=source.slice(source.indexOf('const avaSteps ='),source.indexOf('const avaDraft ='));assert.equal(vm.runInNewContext(definition+';avaSteps.length'),9);assert.ok(preview.includes('AVA 생성 · 준비 중'));assert.ok(preview.includes('disabled'));assert.doesNotMatch(preview,/fetch\(|api\(|localStorage|sessionStorage/);assert.ok(preview.includes("avaDraft.values = avaSteps.map(() => '')"));});
test('resource raw identifiers are confined to closed advanced details',()=>{const context=vm.createContext({esc:x=>String(x),resourceName:()=> 'Test provider',badge:()=>'',resourceMode:()=>'',fmt:()=>''});vm.runInContext(getFunction('resourceCard'),context);const html=context.resourceCard({id:'SECRET_RESOURCE_ID',connectionMode:'INTERNAL_ADAPTER',executionLocation:'PC'});assert.ok(!html.split('<details>')[0].includes('SECRET_RESOURCE_ID'));assert.ok(html.includes('SECRET_RESOURCE_ID'));assert.ok(!html.includes('<details open'));});
test('review copy distinguishes future World and unimplemented AVA',()=>{const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');for(const id of ['hi-thefa','black-box','ava','world'])assert.ok(html.includes(`id="${id}"`));assert.ok(html.includes('현재 World 참여와 AVA 간 자동 실행은 제공하지 않습니다.'));assert.ok(html.includes('고급 기술 보기'));});
