from pathlib import Path

ROOT = Path(__file__).parent
logo = '<span class="brand-icon" aria-hidden="true"></span><span>THE<b>FA</b> Core</span>'
mascot = lambda name, extra='': f'<img class="mascot {extra}" src="assets/mascots/{name}-320.webp" width="160" height="160" alt="" aria-hidden="true" loading="lazy">'

def header(page):
    links = [('index.html#product','제품','home'),('index.html#cases','제품 사례','cases'),('demo.html','공개 체험','demo'),('contact.html','도입 문의','contact')]
    nav = ''.join(f'<a href="{href}"'+(' aria-current="page"' if key==page else '')+f'>{label}</a>' for href,label,key in links)
    return f'''<a href="#main" class="skip-link">본문으로 바로 가기</a>
<div class="reviewbar"><div class="shell"><span>홈페이지 수정안 · 로컬 검토 데모</span><button type="button" data-review>수정 방향 보기 ↗</button></div></div>
<header class="site-header"><div class="shell navrow"><a class="brand" href="index.html" aria-label="THEFA Core 홈페이지">{logo}</a><nav class="navlinks" aria-label="주 메뉴">{nav}</nav><div class="nav-actions"><a class="login-link" href="login.html">로그인</a><a class="button primary compact" href="contact.html">도입 문의 ↗</a><button type="button" class="menu-toggle" aria-expanded="false" aria-controls="mobileNav" aria-label="메뉴 열기">☰</button></div></div><nav class="mobile-nav" id="mobileNav" aria-label="모바일 메뉴">{nav}<a href="login.html">로그인</a></nav></header>'''

def footer():
    return f'''<footer class="footer"><div class="shell"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="index.html">{logo}</a><p>THEFA Core by THE FA<br>흩어진 일을 하나의 흐름으로.<br>제품을 이해하고, 우리 회사에 맞게 시작하세요.</p><p><a class="link" href="mailto:thefa@thefa.kr">thefa@thefa.kr</a></p></div><div class="footer-links"><strong>제품</strong><a href="index.html#product">제품 소개</a><a href="index.html#cases">자체 개발 사례</a><a href="demo.html">공개 체험</a></div><div class="footer-links"><strong>시작하기</strong><a href="login.html">로그인</a><a href="contact.html">도입 문의</a><a href="https://thefa.kr" target="_blank" rel="noopener">THE FA 홈페이지 ↗</a></div><div class="footer-character">{mascot('business')}</div></div><div class="footer-base"><span>주식회사 더파 (The FA Co., Ltd.) · © 2026 THE FA</span><span>검토용 데모 · 화면의 데이터는 가상 예시입니다.</span></div></div></footer>'''

def review():
    return '''<dialog id="reviewDialog" aria-labelledby="reviewTitle"><div class="dialog-inner"><div class="dialog-top"><span class="case-label">공개 홈페이지 수정 방향</span><button type="button" class="dialog-close" data-close aria-label="닫기">×</button></div><h2 id="reviewTitle">가치는 더 잘 보이게,<br>공개 범위는 신중하게.</h2><div class="review-list"><div><b>자체 개발 자산을 제품 사례로</b><span>개발한 영역을 제품군별로 소개하고, 화면 개발·연동 검증 상태를 구분합니다.</span></div><div><b>내부 설계 설명을 고객 경험으로</b><span>제품의 사용 목적과 결과를 보여주며 상세한 내부 구성과 운영 정보는 제외합니다.</span></div><div><b>공개 체험은 가상 데이터로</b><span>사례별 요청과 결과를 살펴볼 수 있습니다. 실제 고객 기록이나 고객 성과는 사용하지 않습니다.</span></div><div><b>상세 자료는 도입 상담으로</b><span>도입 범위와 필요한 자료는 상담 과정에서 확인합니다.</span></div></div><p class="dialog-note">현재 운영 사이트·고객 서비스·저장소 권한은 변경하지 않은 로컬 수정 데모입니다. 고객 서비스 개발은 별도 프로젝트 방의 범위입니다.</p></div></dialog>'''

def page(filename,title,body,kind):
    html=f'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="THEFA Core 제품 소개와 자체 개발 사례의 로컬 검토 데모"><title>{title} · THEFA Core 수정안</title><link rel="icon" href="assets/img/apple-touch-icon.png"><link rel="stylesheet" href="site.css"><script src="cases.js" defer></script><script src="site.js" defer></script></head><body>{header(kind)}<main id="main">{body}</main>{footer()}{review()}</body></html>'''
    (ROOT/filename).write_text(html,encoding='utf-8')

home=f'''
<section class="hero" id="product"><div class="shell"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">THEFA CORE · AI FOR YOUR WORK</p><h1>흩어진 일을,<br><em>하나의 흐름으로.</em></h1><p>여러 도구와 AI 사이를 오가던 업무.<br>요청하고, 결과를 확인하고, 다음 일을 이어가는<br>THEFA Core의 경험을 만나보세요.</p><div class="actions"><a class="button primary" href="demo.html">제품 체험하기 <span aria-hidden="true">→</span></a><a class="button" href="#cases">우리의 제품 사례 <span aria-hidden="true">↗</span></a></div><p class="hero-note">THE FA가 직접 개발한 제품과 업무 사례를 소개합니다.</p></div><div class="workspace" aria-label="가상 업무 화면 예시"><div class="windowbar"><div class="dots" aria-hidden="true"><i></i><i></i><i></i></div><span>THEFA Core · 업무 공간</span><span>화면 예시</span></div><div class="workspace-body"><div class="workspace-head"><span>오늘, 이런 일을 하고 싶어요.</span><span class="tag">가상 업무</span></div><div class="request-card"><small>MY REQUEST</small>이번 주 매장 운영을 정리하고,<br>다음에 할 일을 알려줘.</div><div class="result-row"><span class="check" aria-hidden="true">✓</span><div>매장 현황 요약<small>한눈에 확인하는 운영 내용</small></div></div><div class="result-row"><span class="check" aria-hidden="true">✓</span><div>고객 의견 확인<small>놓치지 않고 살펴볼 내용</small></div></div><div class="result-row"><span class="check" aria-hidden="true">✓</span><div>다음 작업 정리<small>검토하고 이어갈 업무</small></div></div><div class="workspace-bottom"><span>실제 고객 데이터가 없는 예시 화면</span><a href="demo.html?case=core">직접 살펴보기 →</a></div></div></div></div><div class="hero-strip"><span>THE FA가 개발해 온 업무의 영역</span><strong>매장과 고객</strong><strong>회사와 팀</strong><strong>AI와 업무 정보</strong><strong>모바일과 PC</strong></div></div></section>
<section class="section paper" id="cases"><div class="shell"><div class="case-intro"><div><p class="eyebrow">BUILT BY THE FA</p><h2>우리가 만들어 온 제품,<br>업무의 모습으로.</h2></div><p>THE FA의 자체 개발 자산을 제품 사례로 모았습니다.<br>관심 있는 영역을 골라 어떤 일을 돕는지 살펴보세요.</p></div><div class="case-controls"><div class="filters" role="group" aria-label="제품 사례 분류">{''.join(f'<button type="button" class="filter" data-category="{category}" aria-pressed="{str(category=="전체").lower()}">{category}</button>' for category in ['전체','매장·고객','회사·업무','AI·데이터','연동·환경'])}</div><input class="search" id="caseSearch" type="search" placeholder="제품이나 기능 찾기" aria-label="제품 사례 검색"></div><p class="case-count" id="caseCount" aria-live="polite"></p><div class="case-grid" id="caseGrid"></div><p class="empty" id="caseEmpty" hidden>검색한 사례가 없습니다. 다른 제품이나 기능으로 찾아보세요.</p><p class="portfolio-note">자체 개발 사례이며 고객 도입 실적을 의미하지 않습니다. 화면 개발과 연동·기기 검증 중인 기능은 구분하여 표시합니다. 모든 체험 화면은 가상 예시입니다.</p></div></section>
<section class="section" id="how"><div class="shell"><div class="way-heading"><div><p class="eyebrow">A SIMPLE WAY TO WORK</p><h2>요청에서 다음 일까지,<br>자연스럽게.</h2></div>{mascot('checklist')}</div><div class="steps"><article class="step"><span class="step-number">01 / REQUEST</span><h3>하고 싶은 일을 말하세요.</h3><p>문서, 고객 의견, 매장 운영.<br>지금 필요한 일을 중심으로 시작합니다.</p></article><article class="step"><span class="step-number">02 / REVIEW</span><h3>결과를 살펴보세요.</h3><p>정리된 내용과 확인할 항목을 보고,<br>다음에 필요한 판단을 합니다.</p></article><article class="step"><span class="step-number">03 / CONTINUE</span><h3>다음 일을 이어가세요.</h3><p>확인한 결과를 바탕으로,<br>후속 업무와 필요한 작업을 이어갑니다.</p></article></div><div class="actions"><a class="link" href="demo.html">제품 사례로 이 흐름 체험하기 →</a></div></div></section>
<section class="section paper" id="trust"><div class="shell trust-grid"><div class="trust-visual">{mascot('guard')}<div class="trust-word">업무 정보와<br>접근 범위도<br>함께 살핍니다.</div></div><div class="trust-content"><p class="eyebrow">CARE FOR YOUR BUSINESS</p><h2>도입 전부터,<br>데이터와 권한을 신중하게.</h2><p>공개 체험에는 가상 데이터만 사용합니다.<br>실제 도입에서는 필요한 기능과 자료, 사용자별 접근 범위를 함께 확인합니다.</p><div class="trust-points"><div><strong>가상 데이터 체험</strong><span>공개 화면에 실제 고객 기록을 사용하지 않습니다.</span></div><div><strong>필요한 범위 확인</strong><span>도입 목적에 맞는 기능과 접근 범위를 정합니다.</span></div><div><strong>상담 후 상세 안내</strong><span>필요한 연동과 기술 자료를 상담에서 확인합니다.</span></div></div></div></div></section>
<section class="section faq" id="faq"><div class="shell faq-grid"><div><p class="eyebrow">BEFORE YOU START</p><h2>궁금한 점을,<br>먼저 확인하세요.</h2></div><div><details><summary>여기에 소개한 제품은 모두 사용할 수 있나요?</summary><p>개발한 영역을 소개하는 자체 개발 사례입니다. 기능마다 화면 개발, 연동 검증, 사용 가능한 범위가 다릅니다. 실제 사용 범위는 도입 상담에서 확인합니다.</p></details><details><summary>체험 화면은 실제 고객 데이터인가요?</summary><p>모든 공개 체험 화면은 가상 예시입니다. 실제 고객 정보나 고객의 사업 성과를 사용하지 않습니다.</p></details><details><summary>우리 회사의 도구와 연결할 수 있나요?</summary><p>필요한 업무와 현재 사용하는 도구를 알려주시면 연결 가능한 범위와 확인할 항목을 함께 검토합니다.</p></details><details><summary>기존 고객 서비스는 어디에서 사용하나요?</summary><p>로그인 메뉴에서 app.thefacore.com 고객 서비스로 이동할 수 있습니다. 이 홈페이지 수정안은 제품 소개와 공개 체험을 위한 로컬 데모입니다.</p></details></div></div></section>
<section class="cta"><div class="shell cta-row"><div><h2>우리 회사의 일로, 시작해 볼까요?</h2><p>지금 필요한 업무부터 함께 살펴보겠습니다.</p></div><div class="actions"><a class="button primary" href="contact.html">도입 문의하기 →</a><a class="button" href="demo.html">먼저 체험하기</a></div></div></section>
<dialog id="caseDialog" aria-labelledby="caseDialogTitle"><div class="dialog-inner"><div class="dialog-top"><span class="case-label">THE FA 자체 개발 사례</span><button type="button" class="dialog-close" data-close aria-label="사례 닫기">×</button></div><div id="caseDialogContent"></div></div></dialog>'''
page('index.html','제품 소개',home,'home')

demo=f'''
<div class="shell"><section class="sub-hero"><p class="eyebrow">EXPERIENCE THE POSSIBILITIES</p><h1>우리의 제품을,<br><span class="gold">업무 예시로 만나보세요.</span></h1><p>관심 있는 사례를 선택하고, 요청과 결과가 이어지는 모습을 살펴보세요.</p></section><p class="demo-note">가상 데이터 체험 · 실제 고객 정보, 고객 메시지 발송, 외부 업무 실행을 사용하지 않습니다.</p><div class="demo-mobile-select"><label for="demoSelect">체험할 제품 사례</label><select id="demoSelect"></select></div><div class="demo-layout"><aside class="demo-sidebar"><p>THE FA 자체 개발 사례</p><div id="demoOptions"></div></aside><div class="demo-main"><section class="demo-panel"><div class="demo-panel-head"><div><div class="case-label" id="demoCategory"></div><h2 id="demoTitle"></h2><p id="demoDescription"></p></div>{mascot('develop')}</div><span class="tag" id="demoState"></span><div class="field"><label for="demoRequest">이런 업무에 사용해 보고 싶어요.</label><textarea id="demoRequest" maxlength="1000"></textarea></div><div class="sub-actions"><button class="button primary" type="button" id="demoRun">예시 결과 보기 →</button><a class="link" href="index.html#cases">다른 사례 살펴보기</a></div><p class="form-info">입력한 요청을 외부로 전송하지 않습니다. 선택한 제품의 준비된 예시 결과를 표시합니다.</p><p class="result-loader" id="demoProgress" role="status"></p></section><div class="placeholder-result" id="demoPlaceholder">{mascot('research')}<p>예시 결과를 살펴보고,<br>우리 회사에 필요한 일을 떠올려 보세요.</p></div><section class="demo-panel demo-result" id="demoResult" hidden aria-labelledby="resultHeading"><p class="eyebrow">YOUR EXAMPLE RESULT</p><div class="result-title-row"><h2 id="resultHeading"></h2><span class="case-state">가상 예시</span></div><ul class="result-list" id="resultItems"></ul><p class="result-note" id="resultNote"></p><div class="result-footer"><span>실제 고객 기록과 성과를 사용하지 않는 예시입니다.</span><a class="button primary compact" id="resultContact" href="contact.html">이 업무로 도입 문의 →</a></div></section></div></div></div>'''
page('demo.html','제품 체험',demo,'demo')

contact=f'''
<div class="shell form-layout"><section class="form-intro"><p class="eyebrow">LET’S TALK ABOUT YOUR WORK</p><h1>우리 회사에 필요한 일,<br><span class="gold">함께 살펴보겠습니다.</span></h1><p>지금 사용 중인 도구와 해결하고 싶은 업무를 알려주세요.<br>필요한 제품과 연결 범위부터 함께 확인합니다.</p><div class="intro-support">{mascot('talk')}<p>매장 운영부터 회사 업무까지.<br>작은 업무 하나에서 시작해도 좋습니다.</p></div><p><a class="link" href="mailto:thefa@thefa.kr">thefa@thefa.kr ↗</a></p></section><section class="form-card"><h2>도입 문의</h2><p>관심 있는 제품과 업무를 남겨주세요.</p><form id="contactForm"><div class="form-grid"><div class="field"><label for="company">회사·매장 이름</label><input id="company" name="company" autocomplete="organization" maxlength="100" placeholder="회사 또는 매장명" required></div><div class="field"><label for="person">담당자 이름</label><input id="person" name="person" autocomplete="name" maxlength="80" placeholder="담당자명" required></div></div><div class="field"><label for="email">연락받을 이메일</label><input id="email" name="email" type="email" autocomplete="email" maxlength="150" placeholder="name@company.com" required></div><div class="field"><label for="interest">관심 있는 제품 사례</label><select id="interest" name="interest"><option value="">아직 정하지 않았어요</option></select></div><div class="field"><label for="message">해결하고 싶은 업무</label><textarea id="message" name="message" maxlength="2000" placeholder="어떤 업무가 어렵거나 반복되는지 알려주세요." required></textarea></div><label class="checkbox"><input type="checkbox" required><span>검토용 화면임을 확인했습니다. 실제 고객 정보와 민감한 내용을 입력하지 않습니다.</span></label><button class="button primary" type="submit">문의 입력 확인 →</button><p class="form-info">로컬 검토용 데모로, 입력 내용을 저장하거나 전송하지 않습니다.<br>실제 도입 문의는 위 이메일을 이용해 주세요.</p><div class="form-status" id="contactStatus" role="status" hidden></div></form></section></div>'''
page('contact.html','도입 문의',contact,'contact')

login=f'''
<div class="shell form-layout"><section class="form-intro"><p class="eyebrow">WELCOME BACK</p><h1>하던 일을,<br><span class="gold">이어서 시작하세요.</span></h1><p>이미 사용 중인 고객은 THEFA Core 고객 서비스로 이동하세요.<br>제품이 궁금하다면 공개 체험에서 먼저 살펴볼 수 있습니다.</p><div class="intro-support">{mascot('welcome')}<p>오늘 필요한 업무부터,<br>차근차근 이어가세요.</p></div></section><section class="form-card"><h2>THEFA Core 로그인</h2><p>고객 서비스의 로그인 화면으로 안내합니다.</p><div class="login-divider"></div><a class="button primary" href="https://app.thefacore.com/login.html" target="_blank" rel="noopener">고객 서비스 로그인으로 이동 ↗</a><p class="form-info">로그인은 app.thefacore.com에서 진행합니다.<br>이 홈페이지 데모에서는 이메일이나 비밀번호를 수집하지 않습니다.</p><div class="login-divider"></div><p>처음 방문하셨나요?</p><div class="login-links"><a href="demo.html">공개 체험하기 →</a><a href="contact.html">도입 문의하기 →</a></div></section></div>'''
page('login.html','고객 서비스 로그인',login,'login')
print('Generated 4 local review pages. Customer service source and production unchanged.')
