from pathlib import Path
import re

ROOT = Path(__file__).parent
logo = '<img src="assets/brand/core/THEFA_Core_Primary_Dark_web.svg" width="1621" height="424" alt="THEFA Core — a product by THE FA">'
mascot = lambda name, extra='': f'<img class="mascot {extra}" src="assets/mascots/{name}-320.webp" width="160" height="160" alt="" aria-hidden="true" loading="lazy">'

def header(page):
    links = [('index.html#product','제품','home'),('index.html#cases','제품 사례','cases'),('index.html#create','활용·창작','create'),('demo.html','공개 체험','demo'),('contact.html','도입 문의','contact')]
    nav = ''.join(f'<a href="{href}"'+(' aria-current="page"' if key==page else '')+f'>{label}</a>' for href,label,key in links)
    return f'''<a href="#main" class="skip-link">본문으로 바로 가기</a>
<div class="reviewbar"><div class="shell"><span>홈페이지 수정안 · 로컬 검토 데모</span><button type="button" data-review>수정 방향 보기 ↗</button></div></div>
<header class="site-header"><div class="shell navrow"><a class="brand" href="index.html" aria-label="THEFA Core 홈페이지">{logo}</a><nav class="navlinks" aria-label="주 메뉴">{nav}</nav><div class="nav-actions"><a class="login-link" href="login.html">로그인</a><a class="button primary compact" href="contact.html">도입 문의 ↗</a><button type="button" class="menu-toggle" aria-expanded="false" aria-controls="mobileNav" aria-label="메뉴 열기">☰</button></div></div><nav class="mobile-nav" id="mobileNav" aria-label="모바일 메뉴">{nav}<a href="login.html">로그인</a></nav></header>'''

def footer():
    return f'''<footer class="footer"><div class="shell"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="index.html">{logo}</a><p>THEFA Core by THE FA<br>흩어진 일을 하나의 흐름으로.<br>제품을 이해하고, 우리 회사에 맞게 시작하세요.</p><p><a class="link" href="mailto:thefa@thefa.kr">thefa@thefa.kr</a></p></div><div class="footer-links"><strong>제품</strong><a href="index.html#product">제품 소개</a><a href="index.html#cases">자체 개발 사례</a><a href="demo.html">공개 체험</a></div><div class="footer-links"><strong>시작하기</strong><a href="login.html">로그인</a><a href="contact.html">도입 문의</a><a href="https://thefa.kr" target="_blank" rel="noopener">THE FA 홈페이지 ↗</a></div><div class="footer-character">{mascot('business')}</div></div><div class="footer-base"><span>주식회사 더파 (The FA Co., Ltd.) · © 2026 THE FA</span><span>검토용 데모 · 화면의 데이터는 가상 예시입니다.</span></div></div></footer>'''

def review():
    return '''<dialog id="reviewDialog" aria-labelledby="reviewTitle"><div class="dialog-inner"><div class="dialog-top"><span class="case-label">공개 홈페이지 수정 방향</span><button type="button" class="dialog-close" data-close aria-label="닫기">×</button></div><h2 id="reviewTitle">가치는 더 잘 보이게,<br>공개 범위는 신중하게.</h2><div class="review-list"><div><b>자체 개발 자산을 제품 사례로</b><span>개발한 영역을 제품군별로 소개하고, 화면 개발·연동 검증 상태를 구분합니다.</span></div><div><b>내부 설계 설명을 고객 경험으로</b><span>제품의 사용 목적과 결과를 보여주며 상세한 내부 구성과 운영 정보는 제외합니다.</span></div><div><b>공개 체험은 가상 데이터로</b><span>사례별 요청과 결과를 살펴볼 수 있습니다. 실제 고객 기록이나 고객 성과는 사용하지 않습니다.</span></div><div><b>상세 자료는 도입 상담으로</b><span>도입 범위와 필요한 자료는 상담 과정에서 확인합니다.</span></div></div><p class="dialog-note">현재 운영 사이트·고객 서비스·저장소 권한은 변경하지 않은 로컬 수정 데모입니다. 고객 서비스 개발은 별도 프로젝트 방의 범위입니다.</p></div></dialog>'''

def page(filename,title,body,kind):
    html=f'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="THEFA Core 제품 소개와 자체 개발 사례의 로컬 검토 데모"><title>{title} · THEFA Core 수정안</title><link rel="icon" href="assets/img/apple-touch-icon.png"><link rel="stylesheet" href="site.css"><script src="cases.js" defer></script><script src="site.js" defer></script></head><body>{header(kind)}<main id="main">{body}</main>{footer()}{review()}</body></html>'''
    (ROOT/filename).write_text(html,encoding='utf-8')

home=f'''
<section class="hero" id="product"><div class="shell"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">THEFA CORE · AI FOR YOUR WORK</p><h1>흩어진 일을,<br><em>하나의 흐름으로.</em></h1><p>여러 도구와 AI 사이를 오가던 업무.<br>요청하고, 결과를 확인하고, 다음 일을 이어가는<br>THEFA Core의 경험을 만나보세요.</p><div class="actions"><a class="button primary" href="demo.html">제품 체험하기 <span aria-hidden="true">→</span></a><a class="button" href="#cases">우리의 제품 사례 <span aria-hidden="true">↗</span></a></div><p class="hero-note">THE FA가 직접 개발한 제품과 업무 사례를 소개합니다.</p></div><div class="workspace" aria-label="가상 업무 화면 예시"><div class="windowbar"><div class="dots" aria-hidden="true"><i></i><i></i><i></i></div><span>THEFA Core · 업무 공간</span><span>화면 예시</span></div><div class="workspace-body"><div class="workspace-head"><span>오늘, 이런 일을 하고 싶어요.</span><span class="tag">가상 업무</span></div><div class="request-card"><small>MY REQUEST</small>이번 주 매장 운영을 정리하고,<br>다음에 할 일을 알려줘.</div><div class="result-row"><span class="check" aria-hidden="true">✓</span><div>매장 현황 요약<small>한눈에 확인하는 운영 내용</small></div></div><div class="result-row"><span class="check" aria-hidden="true">✓</span><div>고객 의견 확인<small>놓치지 않고 살펴볼 내용</small></div></div><div class="result-row"><span class="check" aria-hidden="true">✓</span><div>다음 작업 정리<small>검토하고 이어갈 업무</small></div></div><div class="workspace-bottom"><span>실제 고객 데이터가 없는 예시 화면</span><a href="demo.html?case=core">직접 살펴보기 →</a></div></div></div></div><div class="hero-strip"><span>THE FA가 개발해 온 업무의 영역</span><strong>매장과 고객</strong><strong>회사와 팀</strong><strong>AI와 업무 정보</strong><strong>모바일과 PC</strong></div></div></section>
<section class="section paper" id="cases"><div class="shell"><div class="case-intro"><div><p class="eyebrow">BUILT BY THE FA</p><h2>우리가 만들어 온 제품,<br>업무의 모습으로.</h2></div><p>THE FA의 자체 개발 자산을 제품 사례로 모았습니다.<br>관심 있는 영역을 골라 어떤 일을 돕는지 살펴보세요.</p></div><div class="case-controls"><div class="filters" role="group" aria-label="제품 사례 분류">{''.join(f'<button type="button" class="filter" data-category="{category}" aria-pressed="{str(category=="전체").lower()}">{category}</button>' for category in ['전체','매장·고객','회사·업무','AI·데이터','연동·환경'])}</div><input class="search" id="caseSearch" type="search" placeholder="제품이나 기능 찾기" aria-label="제품 사례 검색"></div><p class="case-count" id="caseCount" aria-live="polite"></p><div class="case-grid" id="caseGrid"></div><p class="empty" id="caseEmpty" hidden>검색한 사례가 없습니다. 다른 제품이나 기능으로 찾아보세요.</p><p class="portfolio-note">자체 개발 사례이며 고객 도입 실적을 의미하지 않습니다. 화면 개발과 연동·기기 검증 중인 기능은 구분하여 표시합니다. 모든 체험 화면은 가상 예시입니다.</p></div></section>
<section class="section" id="how"><div class="shell"><div class="way-heading"><div><p class="eyebrow">A SIMPLE WAY TO WORK</p><h2>요청에서 다음 일까지,<br>자연스럽게.</h2></div>{mascot('checklist')}</div><div class="steps"><article class="step"><span class="step-number">01 / REQUEST</span><h3>하고 싶은 일을 말하세요.</h3><p>문서, 고객 의견, 매장 운영.<br>지금 필요한 일을 중심으로 시작합니다.</p></article><article class="step"><span class="step-number">02 / REVIEW</span><h3>결과를 살펴보세요.</h3><p>정리된 내용과 확인할 항목을 보고,<br>다음에 필요한 판단을 합니다.</p></article><article class="step"><span class="step-number">03 / CONTINUE</span><h3>다음 일을 이어가세요.</h3><p>확인한 결과를 바탕으로,<br>후속 업무와 필요한 작업을 이어갑니다.</p></article></div><div class="actions"><a class="link" href="demo.html">제품 사례로 이 흐름 체험하기 →</a></div></div></section>
<section class="section paper" id="trust"><div class="shell trust-grid"><div class="trust-visual">{mascot('guard')}<div class="trust-word">업무 정보와<br>접근 범위도<br>함께 살핍니다.</div></div><div class="trust-content"><p class="eyebrow">CARE FOR YOUR BUSINESS</p><h2>도입 전부터,<br>데이터와 권한을 신중하게.</h2><p>공개 체험에는 가상 데이터만 사용합니다.<br>실제 도입에서는 필요한 기능과 자료, 사용자별 접근 범위를 함께 확인합니다.</p><div class="trust-points"><div><strong>가상 데이터 체험</strong><span>공개 화면에 실제 고객 기록을 사용하지 않습니다.</span></div><div><strong>필요한 범위 확인</strong><span>도입 목적에 맞는 기능과 접근 범위를 정합니다.</span></div><div><strong>상담 후 상세 안내</strong><span>필요한 연동과 기술 자료를 상담에서 확인합니다.</span></div></div></div></div></section>
<section class="section faq" id="faq"><div class="shell faq-grid"><div><p class="eyebrow">BEFORE YOU START</p><h2>궁금한 점을,<br>먼저 확인하세요.</h2></div><div><details><summary>여기에 소개한 제품은 모두 사용할 수 있나요?</summary><p>개발한 영역을 소개하는 자체 개발 사례입니다. 기능마다 화면 개발, 연동 검증, 사용 가능한 범위가 다릅니다. 실제 사용 범위는 도입 상담에서 확인합니다.</p></details><details><summary>체험 화면은 실제 고객 데이터인가요?</summary><p>모든 공개 체험 화면은 가상 예시입니다. 실제 고객 정보나 고객의 사업 성과를 사용하지 않습니다.</p></details><details><summary>우리 회사의 도구와 연결할 수 있나요?</summary><p>필요한 업무와 현재 사용하는 도구를 알려주시면 연결 가능한 범위와 확인할 항목을 함께 검토합니다.</p></details><details><summary>기존 고객 서비스는 어디에서 사용하나요?</summary><p>로그인 메뉴에서 app.thefacore.com 고객 서비스로 이동할 수 있습니다. 이 홈페이지 수정안은 제품 소개와 공개 체험을 위한 로컬 데모입니다.</p></details></div></div></section>
<section class="cta"><div class="shell cta-row"><div><h2>우리 회사의 일로, 시작해 볼까요?</h2><p>지금 필요한 업무부터 함께 살펴보겠습니다.</p></div><div class="actions"><a class="button primary" href="contact.html">도입 문의하기 →</a><a class="button" href="demo.html">먼저 체험하기</a></div></div></section>
<dialog id="caseDialog" aria-labelledby="caseDialogTitle"><div class="dialog-inner"><div class="dialog-top"><span class="case-label">THE FA 자체 개발 사례</span><button type="button" class="dialog-close" data-close aria-label="사례 닫기">×</button></div><div id="caseDialogContent"></div></div></dialog>'''
creation='''<section class="section" id="create"><div class="shell"><div class="case-intro"><div><p class="eyebrow">WHAT WILL YOU CREATE?</p><h2>아이디어가 있다면,<br>다음 제작을 시작하세요.</h2></div><p>웹서비스에서 문서·디자인·콘텐츠까지.<br>만들고 싶은 것을 골라 시작 방향을 살펴보세요.</p></div><div class="creation-tabs" role="group" aria-label="만들고 싶은 것" id="creationTabs"></div><div class="creation-preview"><div><span class="case-label">활용·창작 시나리오</span><h3 id="creationTitle"></h3><p id="creationRequest"></p><p class="form-info">새로운 활용 방향의 예시입니다. 제작 범위와 연결 도구는 상담에서 확인합니다.</p></div><div><p class="eyebrow">이런 결과를 준비할 수 있어요.</p><ul id="creationOutputs"></ul><a class="link" href="contact.html">이 아이디어로 도입 문의 →</a></div></div></div></section>'''
cost='''<section class="section paper" id="cost"><div class="shell"><div class="case-intro"><div><p class="eyebrow">A SMALLER TEAM, MORE POSSIBILITIES</p><h2>개발자 5명이 필요한 일,<br>더파코어와 함께한다면?</h2></div><p>기획·초안·반복 수정은 더파코어의 도움을 받고,<br>사람은 판단과 검수에 집중하는 작업 방식을 비교해 보세요.</p></div><div class="cost-note"><strong>가상 비용 비교 · 실제 절감 실적이 아닙니다.</strong><span>같은 제작 범위를 가정합니다. 인원·기간·금액을 바꾸면 예상 비용이 달라집니다. 사람이 맡을 검수·운영과 도구 비용도 포함해 판단하세요.</span></div><div class="cost-layout"><form id="costForm" class="cost-inputs"><fieldset><legend>기존 제작 방식</legend><div class="cost-fields"><label for="basePeople">개발 인원 (명)<input id="basePeople" type="number" min="1" max="100" step="1" value="5" required></label><label for="baseMonths">개발 기간 (개월)<input id="baseMonths" type="number" min="0.5" max="60" step="0.5" value="3" required></label></div></fieldset><fieldset><legend>더파코어를 활용하는 방식 · 가정</legend><div class="cost-fields"><label for="corePeople">참여 인원 (명)<input id="corePeople" type="number" min="1" max="100" step="1" value="2" required></label><label for="coreMonths">개발 기간 (개월)<input id="coreMonths" type="number" min="0.5" max="60" step="0.5" value="3" required></label></div></fieldset><fieldset><legend>비용 가정</legend><div class="cost-fields"><label for="monthlyCost">1인 월 인건비 (만원)<input id="monthlyCost" type="number" min="0" max="10000" step="1" value="500" required></label><label for="toolCost">더파코어·AI·도구 총비용 (만원)<input id="toolCost" type="number" min="0" max="100000" step="1" value="150" required></label><label for="reviewCost">추가 검수·운영 총비용 (만원)<input id="reviewCost" type="number" min="0" max="100000" step="1" value="300" required></label></div></fieldset><p class="cost-assumptions">금액은 설명을 위한 입력값이며 실제 인건비·더파코어 요금이 아닙니다. 같은 1인 월 인건비를 적용하며, 검수 인력이 참여 인원에 포함된 경우 추가 비용을 중복 입력하지 마세요.</p></form><div class="cost-results" aria-live="polite"><p class="eyebrow">가정을 숫자로 비교하면</p><div class="cost-compare"><div><span>기존 방식</span><strong id="baseTotal"></strong><small id="baseDetail"></small></div><div><span>더파코어 활용 가정</span><strong id="coreTotal"></strong><small id="coreDetail"></small></div></div><div class="cost-saving"><span id="savingLabel">가정상 줄어드는 비용</span><strong id="savingTotal"></strong><p id="savingPercent"></p></div><p id="costStatus" class="cost-assumptions"></p><a class="button primary" href="contact.html?case=core">우리 업무로 비교해 보기 →</a><details class="cost-formula"><summary>계산 기준 보기</summary><p>기존 비용 = 인원 × 개월 × 1인 월 인건비<br>더파코어 활용 비용 = 참여 인원 × 개월 × 1인 월 인건비 + 도구 총비용 + 추가 검수·운영 총비용<br>예상 차이 = 기존 비용 − 더파코어 활용 비용</p></details></div></div></div></section>'''
confidential='''<section class="section confidential" id="research"><div class="shell confidential-row"><div><p class="eyebrow">PROTECTED RESEARCH</p><h2>공개할 수 있는 경험은 보여드리고,<br>연구의 핵심은 지킵니다.</h2><p>특허 관련 제품과 비공개 연구는 상세 자료를 공개하지 않습니다.<br>명칭·구조·구현 원리·코드·원문 자료는 이 홈페이지에 포함하지 않습니다.</p></div><div class="confidential-card"><span class="confidential-icon" aria-hidden="true">◇</span><strong>특허 출원 4건</strong><p>상세 기술은 비공개입니다.<br>협업이 필요한 경우 상담에서<br>공개 가능한 범위를 먼저 확인합니다.</p><a class="link" href="contact.html">협업 문의 →</a></div></div></section>'''
experience='''
<section class="section core-experience" id="how" aria-labelledby="experienceTitle">
  <div class="shell">
    <div class="experience-intro">
      <div><p class="eyebrow">EXPERIENCE &amp; VISION</p><h2 id="experienceTitle">더파코어의 다음 경험.<br><span>AVA에서 더파월드까지.</span></h2></div>
      <p>내 일에 맞는 AI에서, 함께 만드는 더 넓은 가능성으로.<br>더파코어가 준비하는 경험과 비전을 만나보세요.</p>
    </div>
    <div class="experience-features">
      <article class="experience-card experience-ava" id="ava" aria-labelledby="avaTitle">
        <div class="experience-card-top"><p class="experience-label">나의 개인 AI · 아바</p><span class="experience-status">개발 미리보기</span></div>
        <div class="experience-brand" aria-hidden="true">AVA<span>✦</span></div>
        <h3 id="avaTitle">내 일에 맞춰,<br>나와 함께하는 AI.</h3>
        <p>내가 선택한 자료와 목표를 바탕으로, 내 업무에 맞는 도움을 받는 개인 AI 경험을 준비합니다.</p>
      </article>
      <article class="experience-card experience-world" id="world" aria-labelledby="worldTitle">
        <div class="experience-card-top"><p class="experience-label">함께하는 미래 · 더파월드</p><span class="experience-status">장기 비전</span></div>
        <div class="experience-brand" aria-hidden="true">THE FA WORLD</div>
        <h3 id="worldTitle">나의 AVA에서,<br>함께 일하는 세계로.</h3>
        <p>서로 다른 전문성과 아이디어가 만나, 개인과 팀이 더 큰 일을 함께 만드는 협업 환경을 향한 장기 비전입니다.</p>
      </article>
    </div>
    <div class="experience-values" aria-label="더파코어가 지향하는 경험">
      <article><h3>이어지는 업무</h3><p>이전 작업을 바탕으로,<br>다음 일을 자연스럽게.</p></article>
      <article><h3>다양한 관점</h3><p>여러 시선으로 살펴보고,<br>중요한 선택은 직접 확인.</p></article>
      <article><h3>알맞은 도움</h3><p>일의 규모와 목적에 맞춰,<br>반복 작업의 부담은 가볍게.</p></article>
      <article><h3>확인하며 완성</h3><p>어디서든 흐름을 살피고,<br>결과를 확인하며 이어가는 방향.</p></article>
    </div>
    <div class="experience-footer"><p>AVA는 개발 미리보기, 더파월드는 장기 비전입니다.<br>기기 간 연속 사용을 포함한 소개 경험은 개발 방향이며, 현재 공개 체험 범위는 체험 페이지에서 확인하실 수 있습니다.</p><a class="link" href="demo.html">현재 공개 체험 보기 →</a></div>
  </div>
</section>'''
home=home.replace('</div><input class="search" id="caseSearch"', '<button type="button" class="filter" data-category="창작·생활" aria-pressed="false">창작·생활</button></div><input class="search" id="caseSearch"')
home=home.replace('<section class="section" id="how">',creation+cost+'<section class="section" id="how">')
home=re.sub(r'<section class="section" id="how">.*?</section>',lambda _:experience,home,count=1,flags=re.S)
home=home.replace('<section class="section faq" id="faq">',confidential+'<section class="section faq" id="faq">')
home=home.replace('THE FA의 자체 개발 자산을 제품 사례로 모았습니다.', '상미부터 Visual Studio Desktop, 단골리턴과 더파코어까지.<br>THE FA의 제품과 자체 제작물을 한곳에 모았습니다.')
home=home.replace('자체 개발 사례이며 고객 도입 실적을 의미하지 않습니다.', 'THE FA의 제품·제작물·개발 영역 사례이며 고객 도입 실적을 의미하지 않습니다. 모든 제품을 더파코어나 Visual Studio로 제작했다는 뜻은 아닙니다.')
home=home.replace('모든 체험 화면은 가상 예시입니다.', '모든 체험 화면은 가상 예시입니다. 비공개 연구와 특허 관련 세부 내용은 포함하지 않습니다.')
home=home.replace('<p class="hero-note">THE FA가 직접 개발한 제품과 업무 사례를 소개합니다.</p>', '<p class="hero-note">업무를 돕고, 새로운 제품과 콘텐츠를 만드는 시작점.</p>')
restored_hero='''<section class="v3-hero" id="product" aria-labelledby="heroTitle"><div class="shell shell--wide v3-hero-grid"><div class="v3-hero-copy"><p class="v3-eyebrow">AI WORK OPERATING SYSTEM</p><h1 id="heroTitle">모든 AI와 도구를,<br><em>하나의 더파코어로.</em></h1><p class="v3-hero-sub">한 번의 지시를, 검증된 실행으로.</p><p class="v3-lead">하고 싶은 일을 말하면, 필요한 업무와 제작을 이어갑니다.<br>문서·디자인·웹서비스부터 회사와 매장의 일까지,<br>결과를 확인하고 다음 작업으로 연결하세요.</p><div class="actions v3-actions"><a class="button primary" href="demo.html">THE FA Core 체험하기 ↗</a><a class="button" href="#cases">우리의 제품 사례</a></div><p class="v3-hero-note">공개 체험은 가상 예시입니다. 실제 제작 범위와 사용 환경은 도입 시 확인합니다.</p><a class="link" href="contact.html">도입 문의 →</a></div><figure class="v3-mesh" aria-label="요청과 제품 경험을 더파코어로 연결하는 가상 예시"><div class="v3-mesh-request"><span class="v3-micro">REQUEST</span><p>“우리 회사에 필요한 웹서비스를 만들고,<br>문서와 디자인, 사용할 화면까지<br>함께 확인해줘.”</p></div><div class="v3-mesh-network"><svg class="v3-mesh-lines" viewBox="0 0 600 280" preserveAspectRatio="none" aria-hidden="true"><path d="M130 30 C240 30 195 140 300 140 M130 100 C210 100 210 140 300 140 M130 175 C220 175 220 140 300 140 M130 250 C230 250 210 140 300 140 M300 140 C390 140 375 30 470 30 M300 140 C390 140 390 100 470 100 M300 140 C390 140 390 175 470 175 M300 140 C390 140 390 250 470 250"/><path class="v3-mesh-route" d="M130 100 C210 100 210 140 300 140 C390 140 390 100 470 100 M130 175 C220 175 220 140 300 140 C390 140 390 175 470 175"/></svg><div class="v3-mesh-bank"><span class="v3-micro">CREATE / WORK</span><span>문서 · 보고서</span><span>디자인 · 콘텐츠</span><span class="is-selected">웹 · 앱 제작</span><span>자료 · 분석</span></div><div class="v3-mesh-core"><span class="v3-micro">ONE CORE</span><strong>THE FA<br>CORE</strong><span>요청과 결과를 하나로</span></div><div class="v3-mesh-bank"><span class="v3-micro">PRODUCTS / BUSINESS</span><span>회사 · 업무</span><span class="is-selected">매장 · 고객</span><span>브랜드 · 마케팅</span><span>제품 · 서비스</span></div></div><div class="v3-mesh-result"><span>만들고 확인할 결과</span><b>문서 · 디자인 · 웹서비스 · 다음 업무</b><div><span>요청</span><i aria-hidden="true">→</i><span>결과 확인</span><i aria-hidden="true">→</i><strong>다음 작업</strong></div></div><figcaption>EXAMPLE · 사용 경험 설명용 가상 예시 · 실제 고객 자료 미사용</figcaption></figure></div></section>'''
home=re.sub(r'<section class="hero" id="product">.*?</section>',lambda _:restored_hero,home,count=1,flags=re.S)
page('index.html','제품 소개',home,'home')

demo=f'''
<div class="shell"><section class="sub-hero"><p class="eyebrow">EXPERIENCE THE POSSIBILITIES</p><h1>우리의 제품을,<br><span class="gold">업무 예시로 만나보세요.</span></h1><p>관심 있는 사례를 선택하고, 요청과 결과가 이어지는 모습을 살펴보세요.</p></section><p class="demo-note">가상 데이터 체험 · 실제 고객 정보, 고객 메시지 발송, 외부 업무 실행을 사용하지 않습니다.</p><div class="demo-mobile-select"><label for="demoSelect">체험할 제품 사례</label><select id="demoSelect"></select></div><div class="demo-layout"><aside class="demo-sidebar"><p>THE FA 자체 개발 사례</p><div id="demoOptions"></div></aside><div class="demo-main"><section class="demo-panel"><div class="demo-panel-head"><div><div class="case-label" id="demoCategory"></div><h2 id="demoTitle"></h2><p id="demoDescription"></p></div>{mascot('develop')}</div><span class="tag" id="demoState"></span><div class="field"><label for="demoRequest">이런 업무에 사용해 보고 싶어요.</label><textarea id="demoRequest" maxlength="1000"></textarea></div><div class="sub-actions"><button class="button primary" type="button" id="demoRun">예시 결과 보기 →</button><a class="link" href="index.html#cases">다른 사례 살펴보기</a></div><p class="form-info">입력한 요청을 외부로 전송하지 않습니다. 선택한 제품의 준비된 예시 결과를 표시합니다.</p><p class="result-loader" id="demoProgress" role="status"></p></section><div class="placeholder-result" id="demoPlaceholder">{mascot('research')}<p>예시 결과를 살펴보고,<br>우리 회사에 필요한 일을 떠올려 보세요.</p></div><section class="demo-panel demo-result" id="demoResult" hidden aria-labelledby="resultHeading"><p class="eyebrow">YOUR EXAMPLE RESULT</p><div class="result-title-row"><h2 id="resultHeading"></h2><span class="case-state">가상 예시</span></div><ul class="result-list" id="resultItems"></ul><p class="result-note" id="resultNote"></p><div class="result-footer"><span>실제 고객 기록과 성과를 사용하지 않는 예시입니다.</span><a class="button primary compact" id="resultContact" href="contact.html">이 업무로 도입 문의 →</a></div></section></div></div></div>'''
page('demo.html','제품 체험',demo,'demo')

contact=f'''
<div class="shell form-layout"><section class="form-intro"><p class="eyebrow">LET’S TALK ABOUT YOUR WORK</p><h1>우리 회사에 필요한 일,<br><span class="gold">함께 살펴보겠습니다.</span></h1><p>지금 사용 중인 도구와 해결하고 싶은 업무를 알려주세요.<br>필요한 제품과 연결 범위부터 함께 확인합니다.</p><div class="intro-support">{mascot('talk')}<p>매장 운영부터 회사 업무까지.<br>작은 업무 하나에서 시작해도 좋습니다.</p></div><p><a class="link" href="mailto:thefa@thefa.kr">thefa@thefa.kr ↗</a></p></section><section class="form-card"><h2>도입 문의</h2><p>관심 있는 제품과 업무를 남겨주세요.</p><form id="contactForm"><div class="form-grid"><div class="field"><label for="company">회사·매장 이름</label><input id="company" name="company" autocomplete="organization" maxlength="100" placeholder="회사 또는 매장명" required></div><div class="field"><label for="person">담당자 이름</label><input id="person" name="person" autocomplete="name" maxlength="80" placeholder="담당자명" required></div></div><div class="field"><label for="email">연락받을 이메일</label><input id="email" name="email" type="email" autocomplete="email" maxlength="150" placeholder="name@company.com" required></div><div class="field"><label for="interest">관심 있는 제품 사례</label><select id="interest" name="interest"><option value="">아직 정하지 않았어요</option></select></div><div class="field"><label for="message">해결하고 싶은 업무</label><textarea id="message" name="message" maxlength="2000" placeholder="어떤 업무가 어렵거나 반복되는지 알려주세요." required></textarea></div><label class="checkbox"><input type="checkbox" required><span>검토용 화면임을 확인했습니다. 실제 고객 정보와 민감한 내용을 입력하지 않습니다.</span></label><button class="button primary" type="submit">문의 입력 확인 →</button><p class="form-info">로컬 검토용 데모로, 입력 내용을 저장하거나 전송하지 않습니다.<br>실제 도입 문의는 위 이메일을 이용해 주세요.</p><div class="form-status" id="contactStatus" role="status" hidden></div></form></section></div>'''
page('contact.html','도입 문의',contact,'contact')

login=f'''
<div class="shell form-layout"><section class="form-intro"><p class="eyebrow">WELCOME BACK</p><h1>하던 일을,<br><span class="gold">이어서 시작하세요.</span></h1><p>이미 사용 중인 고객은 THEFA Core 고객 서비스로 이동하세요.<br>제품이 궁금하다면 공개 체험에서 먼저 살펴볼 수 있습니다.</p><div class="intro-support">{mascot('welcome')}<p>오늘 필요한 업무부터,<br>차근차근 이어가세요.</p></div></section><section class="form-card"><h2>THEFA Core 로그인</h2><p>고객 서비스의 로그인 화면으로 안내합니다.</p><div class="login-divider"></div><a class="button primary" href="https://app.thefacore.com/login.html" target="_blank" rel="noopener">고객 서비스 로그인으로 이동 ↗</a><p class="form-info">로그인은 app.thefacore.com에서 진행합니다.<br>이 홈페이지 데모에서는 이메일이나 비밀번호를 수집하지 않습니다.</p><div class="login-divider"></div><p>처음 방문하셨나요?</p><div class="login-links"><a href="demo.html">공개 체험하기 →</a><a href="contact.html">도입 문의하기 →</a></div></section></div>'''
page('login.html','고객 서비스 로그인',login,'login')
print('Generated 4 local review pages. Customer service source and production unchanged.')
